<?php
header("Access-Control-Allow-Origin: *");
$SVGBF=$_POST['chartBF'];
$SVGBS=$_POST['chartBS'];
$SVGSF=$_POST['chartSF'];
$SVGSS=$_POST['chartSS'];
$SVGAR=$_POST['chartAR'];
$SVGMO=$_POST['chartMO'];
$SVGMD=$_POST['chartMD'];
$SVGOP=$_POST['chartOP'];
$SVGOPS=$_POST['chartOPS'];
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/BF.svg', $SVGBF);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/BS.svg', $SVGBS);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/SF.svg', $SVGSF);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/SS.svg', $SVGSS);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/AR.svg', $SVGAR);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/MO.svg', $SVGMO);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/MD.svg', $SVGMD);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/OP.svg', $SVGOP);
file_put_contents('/var/www/quebio.ca/evaluationbse/pdf/tmp/OPS.svg', $SVGOPS);
$resBF=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/BF.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/BF.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/BS.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/BS.png');
$resBF=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/SF.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/SF.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/SS.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/SS.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/AR.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/AR.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/MO.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/MO.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/MD.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/MD.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/OP.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/OP.png');
$resBS=system('convert /var/www/quebio.ca/evaluationbse/pdf/tmp/OPS.svg /var/www/quebio.ca/evaluationbse/pdf/tmp/OPS.png');
?>